### ISSUE TITLE
Definir quais cores serão usadas no web site.

### ISSUE THREAD

**Issue by wesley-surt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#1]
O link a seguir poderá auxiliar na seleção da paleta: https://color.adobe.com/pt/create/color-wheel. Importante salientar na escolha da harmonia das cores.

**Comment by PedroRodrigues03** [comment]
Abaixo coloquei um exemplo que pode ser usado como paleta de cores, junto com os códigos de cada cor.
Tomei como base as cores colocadas no grupo de Whatsapp.

![paleta_cores_neurokids](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade/assets/99815953/61389b6f-b257-4789-a520-68476cd8cd6c)

**Comment by PedroRodrigues03** [comment]
Abaixo coloquei as cores finais do projeto definidas na última reunião, acredito que esta issue já pode ser fechada.


![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade/assets/99815953/771bc4f3-27a9-440c-b5cf-2be8afd3ab4c)

**Comment by marthabea** [comment]
Boa noite, Pedro! vou encerrar essa issue!
