### ISSUE TITLE
Desenvolver a funcionalidade de ediação das informações de cadastro atrvés do perfil (Editar perfil)

### ISSUE THREAD

**Issue by gustavonovaesh** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#128]

**Comment by wesley-surt** [comment]
Dei uma olhada lá. Tá bem organizado o código só vamos precisar salvar as alterações no json-server ao invés de salvar no localStorage

**Comment by marthabea** [comment]
Bom dia! muito bom, parabéns pelo desenvolvimento. O ponto mencionado pelo Wesley foi feito? se precisar de ajuda, estou à disposição.
