### ISSUE TITLE
Implementar API ViaCEP no formulário de cadastro

### ISSUE THREAD

**Issue by PedroRodrigues03** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#139]

**Comment by PedroRodrigues03** [comment]
@wesley-surt @marthabea @gustavonovaesh 
API para buscar informações pelo CEP já foi implementada, deixei no código (comentado) a possibilidade também de pegar um campo para lograouro caso achem necessário. Aguardo o retorno de vocês!

**Comment by wesley-surt** [comment]
Olhei lá. Tá maneiro o código.

**Comment by marthabea** [comment]
Bom dia! muito legal, parabéns pelo trabalho.
