### ISSUE TITLE
A responsividade das paginas "ajuda_atividades_aplicacao.html", "ajuda_configuracao_conta.html" e "ajuda_acesso_aplicacao.html" estão quebrando

### ISSUE THREAD

**Issue by wesley-surt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#167]
Ao diminuir a janela do navegador - em resoluções de telas menores - a responsividade dá uma quebrada.

**Comment by marthabea** [comment]
Qual seria a resolução? favor informar para que a correção possa ser feita.

**Comment by wesley-surt** [comment]
Na de mobile, apartir de 510 pixel, se não me engano

**Comment by marthabea** [comment]
Obrigada! vou verificar.

**Comment by wesley-surt** [comment]
Por nada!
