### ISSUE TITLE
Cabeçalho mobile das paginas atividade_cores.html e atividade_contagem_objetos.html  está quebrando

### ISSUE THREAD

**Issue by wesley-surt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#175]

**Comment by marthabea** [comment]
Atividade de contagem está resolvido.

**Comment by wesley-surt** [comment]
Fiz um pull request mas no meu pc não está rodando bem. Você fez o push? Talves suas alterações não estejam aparecendo para mim

**Comment by wesley-surt** [comment]
Link do video de jogo:
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade/assets/109616789/25b21a51-d524-4f01-9e52-55d572d79e25


Link do print do cabeçalho na versão mobile:
![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade/assets/109616789/b0f73eda-844b-4445-9498-7d6f56660387)

Aparece assim na minha maquina.
O jogo está exibindo e ocultando as mensagens de erro e acerto rapido. As quantidades sugeridas para clicar não batem com a quantidade de objetos coloridos que aparecem, que é pedido pra ser contado.

copiando e colando esses links na barra de navegação é exibido o conteúdo dos links

**Comment by marthabea** [comment]
Isso está em correção em outra issue. Assim que finalizado, informo para validação.

**Comment by marthabea** [comment]
O ponto levado pelo cabeçalho (mencionado nessa issue) será analisado. Os demais estão sendo reportados em outra issue.

**Comment by wesley-surt** [comment]
blzinha Martha. Misturei os assuntos sem querer kkkkkkkkkkk
