### ISSUE TITLE
Identificar e documentar quais ícones farão parte das páginas.

### ISSUE THREAD

**Issue by wesley-surt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#2]
A página Google fontes é uma boa opção para vasculhar os ícones existentes.

**Comment by marthabea** [comment]
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:notifications:FILL@0;wght@400;GRAD@0;opsz@24&icon link para a página do google fontes.
