### ISSUE TITLE
Preencher as informações sobre o template padrão no repositório do GitHub.

### ISSUE THREAD

**Issue by marthabea** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#31]

**Comment by marthabea** [comment]
Em andamento.

**Comment by PedroRodrigues03** [comment]
Bom dia, Martha! Para ajudar a adiantar as nossas tarefas eu coloquei uma imagem do nosso template padrão, com um pequeno texto. Sinta-se a vontade para realizar qualquer alteração!
Qualquer dúvida acerca do que foi realizado, por favor, não deixe de entrar em contato!

**Comment by marthabea** [comment]
Muito bom, Pedro! obrigada!
