### ISSUE TITLE
Construir página principal em HTML e CSS

### ISSUE THREAD

**Issue by gustavonovaesh** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#34]

**Comment by PedroRodrigues03** [comment]
Seção de cards "para pais e profissionais" concluida.

**Comment by PedroRodrigues03** [comment]
Todas as seções estão concluídas, faltando apenas colocar a versão final do header e os ícones de redes sociais.

**Comment by marthabea** [comment]
ícones inseridos! irei subir a versão atualizada.
