### ISSUE TITLE
Desenvolver tela de cadastro

### ISSUE THREAD

**Issue by marthabea** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#55]

**Comment by wesley-surt** [comment]
Esta tela também foi finalizada. Alguns comportamentos forram ampliados, em relação aos campos de inputs, para facilitar a seleção deles. Espero que testem os campos, responsividade e verfiquem a montagem da tela se está em conformidade com o que é pedido no figma. Espero o retorno de vocês @marthabea, @PedroRodrigues03, @gustavonovaesh.

**Comment by wesley-surt** [comment]
Se puderem reparar, meus arquivos css estão classificados e separados por uma hierarquia pasta, de acordo com as telas que construí para evitar conflitos de estilos entre tags, seletores e possíveis classes e ids idênticos que possamos criar.

**Comment by PedroRodrigues03** [comment]
Por mim está muito bom! Pode dar como concluído.
Só uma ideia que seria no campo "nos conte um pouco sobre voce", fazer com que o digite algo sobre voce esteja alinhado a borda superior esquerda, assim quando a pessoa clicar para escrever o cursor começaria da forma como escrevemos normalmente.
Depois me diz o que acha sobre essa ideia!

**Comment by wesley-surt** [comment]
@PedroRodrigues03 Acho uma observação muito boa. Eu até que tentei, kkkkk, mas sem sucesso. Vou pesquisar mais um pouco, mas, também aceito dicas e sugestões, quem tiver. Deu uma pesquisada durante a escrita html e css mas não encontrei nada que ajudasse.
