### ISSUE TITLE
Desenvolver tela atividades escolares

### ISSUE THREAD

**Issue by PedroRodrigues03** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#56]

**Comment by wesley-surt** [comment]
@PedroRodrigues03 @marthabea @gustavonovaesh 
Assim como as outras issues, aguardo o feedback de vocês nessa. E como na programação nada se cria, tudo se copia; copiei a estutura de html e css do Pedro, da página principal  e fiz alguns ajustes para moldar na tela de atividades escolares... kkkkkk. Os textos ainda estão em lorem ipsum.

**Comment by PedroRodrigues03** [comment]
Bom dia, @wesley-surt ! Ficou muito bacana! E não há problema nenhum em copiar kkkkkkk eu também copiei as suas estruturas de responsividade para cabeçalho e rodapé, estamos juntos nessa, todo mundo se ajudando!
Dito isso, pode dar a tela como concluída, por mim, nenhuma consideração a ser feita.
