### ISSUE TITLE
Desenvolver tela de perfil

### ISSUE THREAD

**Issue by marthabea** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#57]

**Comment by wesley-surt** [comment]
@gustavonovaesh Meu navegador está com algum problema kkkk, assim como aconteceu quando abri a tela do Pedro no navegador. Mas até onde meu navegador me permitiu ver, está muito bom.

**Comment by marthabea** [comment]
Rodando liso! muito legal, parabéns Gustavo!
