### ISSUE TITLE
Desenvover tela da área infantil

### ISSUE THREAD

**Issue by marthabea** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#60]

**Comment by PedroRodrigues03** [comment]
@marthabea @gustavonovaesh @wesley-surt 
Tela em revisão, faltando apenas a definição das outras duas atividades que serão elaboradas para implementação das imagens, textos e links nos devidos cards!

**Comment by wesley-surt** [comment]
@PedroRodrigues03 Pedro, a tela está rodando tudo muito bom. A responsividade também está muito boa. Por mim pode dar como concluída.

**Comment by wesley-surt** [comment]
As imagens tem que se relacionar com o tipo de jogo, né? Se for, quando eu montar o jogo eu te mando a imagem.

**Comment by PedroRodrigues03** [comment]
Sim sim, assim que todo mundo definir o tipo de jogo, imagem e descrição da atividade eu adiciono e fecho essa issue, os links a gente ajeita quando todo mundo subir na main, que ai vou ter o nome certo do html de cada página.

**Comment by gustavonovaesh** [comment]
Nessa tela, a sobra dos cards pode se laranja pra manter o padrão das cores da sobra dos card da página inicial.
