### ISSUE TITLE
Pesquisar as informações para as telas estáticas de conteúdo que serão desenvolvidas.

### ISSUE THREAD

**Issue by marthabea** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#70]

**Comment by marthabea** [comment]
Bom dia meus amigos! previsão de finalização da pesquisa + inserção dos textos nas nossas telas diretamente no figma fica para hoje. Notei pontos de melhoria que estou aplicando e assim que estiver finalizado, posto para vocês avaliarem!

**Comment by marthabea** [comment]
As telas de conteúdo que estão sendo trabalhadas são: Deficiência intelectual, transtorno específico da aprendizagem, espectro autista, transtornos motores, déficit de atenção e transtorno da comunicação.

**Comment by marthabea** [comment]
Boa noite! os conteúdos das telas que estavam pendentes foram inseridos dentro de um template web para que vocês possam avaliar. Fiquem à vontade! **quando finalizarem a leitura e derem o ok, me avisem para que eu possa personalizar de acordo com o padrão que definimos.**

Obs: está dentro do nosso grupo do FIgma. 

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade/assets/89950149/1e35a7d5-0cea-4941-b1af-39edd9be7a67)

**Comment by wesley-surt** [comment]
Vi o conteúdo e está bem escrito com bastante informação
