### ISSUE TITLE
Elaborar uma pesquisa de atividades escolares voltadas para crianças neurodivergentes

### ISSUE THREAD

**Issue by wesley-surt** [ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-neurodiversidade#89]

**Comment by wesley-surt** [comment]
@PedroRodrigues03 @gustavonovaesh @marthabea 
Realizei umas pesquisa pelas atividades escolares voltadas para crianças e já as moldei no estilo de criação das nossas páginas no figma. Espero pelo retorno de vocês. Talvez eu altere as imagens ilustrativas no início das páginas, que se adaptam melhor ao contexto.

**Comment by marthabea** [comment]
Boa tarde! muito bom a organização dos conteúdos, do jeito que está ficou perfeito! parabéns.
